Repository eclipse/mwe, pull requests merged in 2020-10, with the labels that each got.

#169 Update version to 2.12.0/1.6.0
  features/org.eclipse.emf.mwe.core-feature/feature.xml
  features/org.eclipse.emf.mwe.core-feature/pom.xml
  features/org.eclipse.emf.mwe.doc-feature/feature.xml
  features/org.eclipse.emf.mwe.doc-feature/pom.xml
  features/org.eclipse.emf.mwe.sdk-feature/feature.xml
  features/org.eclipse.emf.mwe.sdk-feature/pom.xml
  features/org.eclipse.emf.mwe.ui-feature/feature.xml
  features/org.eclipse.emf.mwe.ui-feature/pom.xml
  features/org.eclipse.emf.mwe2.language.sdk-feature/feature.xml
  features/org.eclipse.emf.mwe2.language.sdk-feature/pom.xml
  features/org.eclipse.emf.mwe2.launcher-feature/feature.xml
  features/org.eclipse.emf.mwe2.launcher-feature/pom.xml
  features/org.eclipse.emf.mwe2.runtime.sdk-feature/feature.xml
  features/org.eclipse.emf.mwe2.runtime.sdk-feature/pom.xml
  features/pom.xml
  maven/org.eclipse.emf.mwe2.parent/pom.xml
  maven/org.eclipse.emf.mwe2.repository/pom.xml
  maven/org.eclipse.emf.mwe2.target/pom.xml
  plugins/org.eclipse.emf.mwe.activities/META-INF/MANIFEST.MF
  plugins/org.eclipse.emf.mwe.activities/pom.xml
  plugins/org.eclipse.emf.mwe.core/META-INF/MANIFEST.MF
  plugins/org.eclipse.emf.mwe.core/pom.xml
  plugins/org.eclipse.emf.mwe.doc/META-INF/MANIFEST.MF
  plugins/org.eclipse.emf.mwe.doc/pom.xml
  plugins/org.eclipse.emf.mwe.ui.simpleEditor/META-INF/MANIFEST.MF
  plugins/org.eclipse.emf.mwe.ui.simpleEditor/pom.xml
  plugins/org.eclipse.emf.mwe.ui/META-INF/MANIFEST.MF
  plugins/org.eclipse.emf.mwe.ui/pom.xml
  plugins/org.eclipse.emf.mwe.utils/META-INF/MANIFEST.MF
  plugins/org.eclipse.emf.mwe.utils/pom.xml
  plugins/org.eclipse.emf.mwe2.language.ide/META-INF/MANIFEST.MF
  plugins/org.eclipse.emf.mwe2.language.ide/pom.xml
  plugins/org.eclipse.emf.mwe2.language.ui/META-INF/MANIFEST.MF
  plugins/org.eclipse.emf.mwe2.language.ui/pom.xml
  plugins/org.eclipse.emf.mwe2.language/META-INF/MANIFEST.MF
  plugins/org.eclipse.emf.mwe2.language/pom.xml
  plugins/org.eclipse.emf.mwe2.launch.ui/META-INF/MANIFEST.MF
  plugins/org.eclipse.emf.mwe2.launch.ui/pom.xml
  plugins/org.eclipse.emf.mwe2.launch/META-INF/MANIFEST.MF
  plugins/org.eclipse.emf.mwe2.launch/pom.xml
  plugins/org.eclipse.emf.mwe2.lib/META-INF/MANIFEST.MF
  plugins/org.eclipse.emf.mwe2.lib/pom.xml
  plugins/org.eclipse.emf.mwe2.runtime/META-INF/MANIFEST.MF
  plugins/org.eclipse.emf.mwe2.runtime/pom.xml
  plugins/pom.xml
  tests/org.eclipse.emf.mwe.tests/META-INF/MANIFEST.MF
  tests/org.eclipse.emf.mwe.tests/pom.xml
  tests/org.eclipse.emf.mwe2.language.tests/META-INF/MANIFEST.MF
  tests/org.eclipse.emf.mwe2.language.tests/pom.xml
  tests/pom.xml
Labels: releng

#167 Writer: Make encoding configurable
  plugins/org.eclipse.emf.mwe.utils/src/org/eclipse/emf/mwe/utils/Writer.java
Labels: enhancement

#172 [#156] Add quickfix to remove unused variables
  plugins/org.eclipse.emf.mwe2.language.ui/src/org/eclipse/emf/mwe2/language/ui/quickfix/Mwe2QuickfixProvider.java
Labels: new_feature
